name: Python package tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Lint with ruff
        run: uvx ruff check .
      - name: Format with ruff
        run: uvx ruff format --check .
      - name: Test with unittest
        run: uv run python -m unittest discover -s tests
      - name: Lint with mypy
        run: uvx mypy feedendum